version: '3.8'

services:

  # Servicio de la aplicación
  back:
    build:
      context: ./
    container_name: back
    image: melany555/3apis-back:latest
    ports:
      - "80:80"
    restart: always
